server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://mixpedia-fastapi-50799312352.asia-northeast3.run.app/;
        proxy_set_header Host mixpedia-fastapi-50799312352.asia-northeast3.run.app;
    }
}